### PR TITLE
Episode 6 notes

### PR DESCRIPTION
**Pull request by nvk**

### CODE REVIEW

**Comment by nvk** [comment]
add
- SATSCARD Domain upgraded to .com http://satscard.com

**Comment by nvk** [comment]
Peach launch peachbitcoin.com

**Comment by nvk** [comment]
poolin insolvent

**Comment by nvk** [comment]
mempool lightning explorer

**Comment by nvk** [comment]
ATEC608A NRND

**Comment by jonnymarshall** [comment]
> ATEC608A NRND

Hey NVK not sure what this is about. I also read [your tweet about this](https://twitter.com/nvk/status/1568641899501875201?s=20&t=F6SCPD5eS7cvzKO8VEGWVw) but not sure what to do for this. Do you have a link or something so I can find out a bit more info and add it to the notes?

**Comment by jonnymarshall** [comment]
> any new version of nunchuk since last show?

Only thing I can see is they now [support Bitbox02 as of 3 days ago](https://github.com/nunchuk-io/libnunchuk/commit/a12061ef0b61afcfd5df0488789ebb1b19adc10c).

**Comment by nvk** [comment]
> > ATEC608A NRND
> 
> Hey NVK not sure what this is about. I also read [your tweet about this](https://twitter.com/nvk/status/1568641899501875201?s=20&t=F6SCPD5eS7cvzKO8VEGWVw) but not sure what to do for this. Do you have a link or something so I can find out a bit more info and add it to the notes?

Yeah, just put that and the tweet link on noteworthy and I can edit later.

**Comment by nvk** [comment]
> > any new version of nunchuk since last show?
> 
> Only thing I can see is they now [support Bitbox02 as of 3 days ago](https://github.com/nunchuk-io/libnunchuk/commit/a12061ef0b61afcfd5df0488789ebb1b19adc10c).

I don’t think that’s out yet. CC @hugohn

**Comment by nvk** [comment]
The Ethereum merge, gotta mention.

**Comment by hugohn** [comment]
No update this week. But we have several in the coming weeks :) (mk4, Primary Key, BIP21, Bitbox02 support etc.)

**Comment by justinmoon** [comment]
Some interesting ones from our meetup

- Carl dong leaving core bitcoin development https://twitter.com/carl_dong/status/1565108387842560000
- private information retrieval block explorer https://btc.usespiral.com/
- treasury update on tornado cash https://www.nobsbitcoin.com/ofac-tornado-sanctions-update/
- wallet labeling bip https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-August/020887.html
- zero knowledge bitcoin blockchain state prover https://github.com/bitcoin-stark/khepri

**Comment by nvk** [comment]
coming COLDCARD 5.0.7 TBA

- Enhancement: In older versions, multisig NFC import not offered if a MicroSD card was inserted, now this option provided Settings > Multisig Wallets > Import via NFC. NFC has to be enabled for this option to be visible in the menu.
- Enhancement: New menu wraparound settings which allow you to scroll past top and bottom of any menu (Settings > Menu Wrapping).
- Enhancement: Allow import of new descriptor type which specify both internal/external in single string (ie. ../<0;1>/..). We still export in older format.
- Enhancement: Ignore HSM command over USB, by default. To enable and use HSM features, go to Advanced/Tools > Enable HSM > Enable
- Enhancement: Dynamic HSM Whitelisting. Foreign outputs can be attested-to by signing them with private key corresponding to the address specified in HSM policy. Attestation signature MUST be provided in PSBT in a new proprietary field. Thanks to [@straylight-orbit](https://github.com/straylight-orbit) for this powerful new feature.
- Bugfix: Correct parsing of unknown fields in PSBT: they are now passed through.
- Bugfix: Share single address over NFC from address explorer menu.
- Bugfix: Using lots of trick pins (7+), could lead to a case where the Coldcard would not accept the main pin, but trick pins continued to work. This release adds a workaround to avoid getting into that situation, and new units from the factory will ship with an updated bootrom (version 3.1.5).

**Comment by nvk** [comment]
> Some interesting ones from our meetup
> 
> * Carl dong leaving core bitcoin development https://twitter.com/carl_dong/status/1565108387842560000
> * private information retrieval block explorer https://btc.usespiral.com/
> * treasury update on tornado cash https://www.nobsbitcoin.com/ofac-tornado-sanctions-update/
> * wallet labeling bip https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-August/020887.html
> * zero knowledge bitcoin blockchain state prover https://github.com/bitcoin-stark/khepri
> * mullvad vpn hardware https://mullvad.net/en/blog/2022/9/19/mullvad-creates-a-hardware-company/

@jonnymarshall these too... looks like all noteworthy, not releases

**Pull request merged**
